### ISSUE TITLE
have group admin users directed to their group admin page upon login

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#100]

**Comment by Matt-Holland** [comment]
route should be /groups/{ID}/admin

**Comment by matinieves** [comment]
Currently admin group users are redirected to the Group events (`/events`) page. There they can switch between `members` and `events` using the navigation tabs.  However we can change it.

**Comment by Matt-Holland** [comment]
@rabble is there enough info here for you to carry this out?

**Comment by Matt-Holland** [comment]
route for logged in group Organizer should be /members

**Comment by harpojaeger** [comment]
Organizers are directed to the right place (/members), but admins are directed to (admin/dashboard).  @Matt-Holland, it sounds like you wanted them sent to /groups/{ID}/admin?

**Comment by harpojaeger** [comment]
We're using with /admin/dashboard.
