### ISSUE TITLE
BUG: Location preview image for events is broken

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#112]
![event_location_broken](https://cloud.githubusercontent.com/assets/1071298/25915410/3e8933fc-3576-11e7-9cb1-8e7c2788bc5a.png)

**Comment by agustinrhcp** [comment]
The event has wrong coordinates: `longitude: -98.4999989109997, latitude: 39.7599977890005`. I'll look for a way to don't show a broken map when this happens.

**Comment by Matt-Holland** [comment]
tested on Dev, Accepted
