### ISSUE TITLE
Add method to Person which looks for the phone number

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#116]
AN stores phone number as a custom field cellphone... we need a helper method in person to read / write to that.

**Comment by Matt-Holland** [comment]
closing, as this was added at some point to Person.rb:

def custom_field_to_phone_number
    potential_fields = [ 'Phone Number', 'Phone', 'phone', "2 Phone"]

    potential_fields.each do |field_name|
      unless custom_fields[field_name].nil?  
        phone_numbers.create(:number => custom_fields[field_name])
      end
    end
  end
