### ISSUE TITLE
static maps sometimes broken

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#119]
Looks like the API key isn't always being included maps which cause them not to load. Not sure why as it's in teh code and it works on some deployments and not others.

**Comment by agustinrhcp** [comment]
Can you upload an example of a not working map? Because I just found a location with wrong coordinates, maybe that's it

**Comment by rabble** [comment]
no it's definately not bad locations... i looked in the url and it's not including the key

**Comment by agustinrhcp** [comment]
You are right. Checking it

**Comment by rabble** [comment]
This has been fixed.
