### ISSUE TITLE
[import]: create a set of sample events and rsvps, in the Advocacy Commons Action Network install  (NOT the Indivisible install)

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#12]
(this is expanded from the original issue "import into Affinity all(?) the data on events for a particular Indivisible chapter (within a date range?)" )

**Comment by harpojaeger** [comment]
Worth making a new group in the AC AN network that these events will go in?  That way, we can try out our authentication too. ( #5 )

**Comment by Matt-Holland** [comment]
We have 50+ groups created in our AC AN network already, but fine with me to create a new one too.

**Comment by harpojaeger** [comment]
2 sample events w/ RSVPs are now in the Arizona group in the AC AN network.
