### ISSUE TITLE
/events Add date of event & Sort by Event Date

### ISSUE THREAD

**Issue by setch-l** [advocacycommons/advocacycommons#123]
Organizers need to see the date of the event on /events. 
Organizers need to be able to sort by event date on /events
Events should be default to most farthest date in the future. 
See attached mock for new layout
![events-date-sort](https://cloud.githubusercontent.com/assets/6765558/25974107/2c9734b4-3675-11e7-9069-7ec58b1de16a.png)

**Comment by Matt-Holland** [comment]
I'm removing this from the current project, for more attention later on.

**Comment by rabble** [comment]
this is already done and deployed
