### ISSUE TITLE
/events Allow users to click to email event host

### ISSUE THREAD

**Issue by setch-l** [advocacycommons/advocacycommons#124]
![events-date-sort](https://cloud.githubusercontent.com/assets/6765558/25974184/aaa0fa02-3675-11e7-8ed0-bab06054f74b.png)
On the /events screen Event Organizer name is linked. 
Clicking on the name triggers email organizer through the browser's default email option.

See attached png.

**Comment by Matt-Holland** [comment]
I'm taking this out of this project, and putting it into the backlog for more attention on a different sprint.

**Comment by agustinrhcp** [comment]
this PR #172 also includes this

**Comment by harpojaeger** [comment]
@agustinrhcp I don't see this on dev at the moment.  Am I missing something?

**Comment by agustinrhcp** [comment]
@harpojaeger That's because the organizer hasn't been pulled from action network. We need to rerun the imports.

**Comment by harpojaeger** [comment]
Great, let me know when that's done.

**Comment by harpojaeger** [comment]
@agustinrhcp UI is a bit confusing as is.  This should either follow the above mockup exactly (i.e. add in 'hosted by'), or there should be enough space between the name of the organizer & the event venue that it's not too busy.  See screenshot.
![screen shot 2017-05-18 at 5 11 06 pm](https://cloud.githubusercontent.com/assets/4314013/26223671/15e4d500-3bed-11e7-829e-6690de903811.png)

**Comment by setch-l** [comment]
The original story is to allow an organizer to email an event host directly. However when I'm in production and I tap on the even host's name in the /events view - it takes me to the profile screen for the host rather than allowing me to email them directly. I have a new story to update this screen. My recommendation is to close this story and do the new one. It will make more sense in the new screen.
