### ISSUE TITLE
Create Print Version of RSVP List w/ spaces for additional attendees

### ISSUE THREAD

**Issue by setch-l** [advocacycommons/advocacycommons#126]
A user clicks the print icon on the RSVP list screen. An overlay appears with a preview of the sign-in sheet - see attached. Then the print dialogue box appears on top. User follows print instructions for the browser. 

For print version - I've added column headers and moved the email from under the name to the right of the name. I replaced the toggle option with check boxes. The boxes could be the same with the Y and N in the middle and the organizer can circle or shade them. The mock is a rough guide - do what's easiest 
![print-attendance](https://cloud.githubusercontent.com/assets/6765558/25974429/fce8c5f0-3676-11e7-8777-57f39cbe1de2.png)

Acceptance Criteria for Print Sheet: 
The print sheet also contains the Group name in the upper left, Event name in upper right. 
The url to enter attendance data. 
Needs 20 blank spaces at the end of the sheet. If less than 20, print second sheet full of blanks. 
Print sheet needs to contain column for adding phone number for new attendees.

**Comment by rabble** [comment]
The generated PDF looks nothing like the mockups. 

[attendances.pdf](https://github.com/advocacycommons/advocacycommons/files/1008957/attendances.pdf)

**Comment by matinieves** [comment]
New version ready to test on `https://dev-advocacycommons-pr-175.herokuapp.com/events`

**Comment by matinieves** [comment]
I'm still working on it, but you can take a look to the styles meanwhile.
