### ISSUE TITLE
[import]: import the set of users marked as "RSVP" for a particular event, into Affinity database

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#14]

**Comment by Matt-Holland** [comment]
- you choose one event at a time to manage
- the sync should happen when you choose the event

so,

a) i see a list of events from which to choose
b) I select one from the list
c) I see a “waiting” message while we retrieve the latest list of RSVP’s for the event, and the latest event details
d) I see the event details and the list of RSVP’s displayed

**Comment by davidtaylor** [comment]
AN does not have a standard field for phone :( 

Lets check to see if there is a custom field for phone for the user on import that we can map to the phone field in the OSDI data model.  Or we should decide to drop the phone filed from the RSVP user list view

**Comment by Matt-Holland** [comment]
I think Affinity needs "phone" regardless of whether OSDI has it or not. Should be a one-many relation (a person has multiple phone numbers) just like OSDI does with email.

**Comment by scottwillson** [comment]
There is progress towards this in the import-action-network-import-event-people branch.

Things to-do before it's ready to use
 * Fetch person records and put more than name: 'TBD' in our DB!
 * test new attendance, new person
 * test existing attendance, person, no updates
 * test existing person, no updates
 * test existing attendance, person, update attendance
 * test existing attendance, person, update person
 * test existing attendance, person, update person, attendance
 * test existing person, update person
 * Ensure all attendance, event, and people properties are imported

**Comment by Matt-Holland** [comment]
right now we import people, and we import events, but we ALSO need their attendance tracking. Attendance is a separate API endpoint on ActionNetwork. Need to import those and update the joiner table on our end.

**Comment by Matt-Holland** [comment]
*some* of the code for this is written. We do store the personID correctly but not the event related to the "attendance" value. Currently broken.

**Comment by agustinrhcp** [comment]
If I understood correctly this is already working. I just ran the import and the Attendance already has both person and event.
