### ISSUE TITLE
View full person record as it's own page

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#151]
As an organizer of a group, i should be able to view a person's records on it's own page with a list of groups they're a member of, events they've RSVP'd for, and attended. In the future we'll display more information about an individual user's records.

**Comment by rabble** [comment]
So this isn't done we get the member's page but it doesn't show any information about them beyond their name. We need their events groups, and contact information

![screen shot 2017-05-18 at 1 46 31 pm](https://cloud.githubusercontent.com/assets/76/26222877/73ed58f6-3bd0-11e7-81bf-113b8a062c5a.png)

**Comment by agustinrhcp** [comment]
@rabble The test users have no data. I'll try with the imported ones.
