### ISSUE TITLE
Push new / edited person records back to ActionNetwork (or other endpoints)

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#153]
When a person's record is edited or created we should push that information out to Action Network so the data stays in sync.

**Comment by agustinrhcp** [comment]
Hey @rabble 
Take a look at this: https://github.com/advocacycommons/advocacycommons/compare/create-attendee...wip-sync-an

That syncs both the person and his attendances to action network. I created an after_create action, but I don't think that's the best approach, I just want to know what you think and when should we sync.

**Comment by rabble** [comment]
This doesn't seem to be working for me when i tested it. See bugs #198, #193.

**Comment by setch-l** [comment]
I tested this by creating a new attendee in an event and then logging into action network and downloading the csv file for the event to verify the new attendee was in the list. It worked and I'm closing this issue.
