### ISSUE TITLE
add "import from Facebook Button"

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#158]
From /events an Organizer or Admin sees an "Import Event from Facebook" button

[screenshot](http://mattplans.altervista.org/affinity/userstoryimages/FacebookEventImport/events-date-sort-facebook-import.png)

User stories for this milestone are here: [https://docs.google.com/spreadsheets/d/1fmz6CKYURrGlDn-nugK6GJmNb5DMzJfYVnHSSVslyUY/edit#gid=1407566793](https://docs.google.com/spreadsheets/d/1fmz6CKYURrGlDn-nugK6GJmNb5DMzJfYVnHSSVslyUY/edit#gid=1407566793)

**Comment by matinieves** [comment]
@Matt-Holland @rabble What is the correct flow? The `import from Facebook` button should always be visible, and if the user has not linked his Facebook account, will he show the login dialog with Facebook? Otherwise we continue the flow described in the tickets #159 to #169?

**Comment by matinieves** [comment]
Or should we add a `connect with Facebook` button on the profile page? and only show the `import from Facebook` button if the user has linked it's Facebook account?
