### ISSUE TITLE
retrieve Facebook event attendees

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#162]
Using the event mapping from ticket #160 and stored in #161, retrieve the first name, last name, and scoped FB ID for every person marked as "attending" or "interested" in the FB event.

## NEED TO DISCUSS
**OPEN QUESTION:** Should we authenticate as the Affinity app, or as the user who is logged in to Affinity???

**Comment by matinieves** [comment]
This code is already implemented. Needs #164 finished to be tested.

**Comment by Matt-Holland** [comment]
closing this because it has been done.
