### ISSUE TITLE
Display matching dialog of FB and Affinity attendees to user

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#164]
After the matching is attempted in #163 , User sees a page with a two-column list of names. On the left is the First name and last name of a person retrieved from Facebook as a "yes will attend".  On the right is the First Name, Last Name, email address, and if present physical address, of a person Affinity suggests as a match based on a same (or similar?) name. there is a checkmark between the two columns, labelled "match", which when clicked turns green, and records the scoped FB ID for the person on the left into the record for the Affinity member on the right.

[screenshot](http://mattplans.altervista.org/affinity/userstoryimages/FacebookEventImport/FB-Affinity-Event-RSVP-Match.png)

**Comment by setch-l** [comment]
Please use this screenshot. 
Dark blue check-marks indicate match. 
Optional light blue check-marks indicate possible match. 
![a-2-2-b2-synch-rsvps](https://cloud.githubusercontent.com/assets/6765558/26109885/9f1c89ba-3a1e-11e7-8c26-33f81dedffda.png)

**Comment by Matt-Holland** [comment]
this is done
