### ISSUE TITLE
Create Attendee Data Entry Screen

### ISSUE THREAD

**Issue by setch-l** [advocacycommons/advocacycommons#177]
User can enter email, first & last name and phone. [screenshot](http://mattplans.altervista.org/affinity/userstoryimages/a-2-data-entry-form2.png)
Clicking on the Add optional address link drops the done button down and the address fields appear. [Screenshot w/ address fields](http://mattplans.altervista.org/affinity/userstoryimages/a-2-data-entry-form-with-address2.png)
**Use Case 1**
User enters email and the backend does a look up for that email address and populates the rest of the fields if match is found. 
User can only click done - they are not permitted to edit the fields. 
**Use Case 2**
If user enters data into any other field except email first and then returns to email field, the data they entered is temporarily stored and look up is performed. If there is an email match, the database overwrites the data entered. User is not allowed to edit fields, clicks done to save. 
**User Case 3**
If user enters data into any other field except email first and then returns to email field, the data they entered is temporarily stored and look up is performed. If there is not a look-up match, then the user can continue to enter info.

**Comment by rabble** [comment]
It should try and look up people as you type so you can select one we already know about... i think...

Anyway, this doesn't work... it throws an error when you try and add somebody

POST http://dev-advocacycommons-pr-191.herokuapp.com/events/1/attendances.json 500 (Internal Server Error)
