### ISSUE TITLE
add more information to person page

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#181]
ON the member page you should be able to see lots more info about the person, all the contact we have, plus what events they organized, created, attended, and other activity on affinity. 

We should show their contact information, what groups they're members of (we'll adjust this maybe in the future).

Then when we list a person's name we should start linking to their person page. 

http://www.affinity.works/groups/3/members/335

**Comment by Matt-Holland** [comment]
Here is a priority list of items person page should include:

1) list of events to which the person has rsvp'd, marked as "rsvp'd" if they rsvp'd but we do not know if they attended, "attended" if we have record that they attended, and "missed" if we have a record that they did NOT attend. Note that these are different options than the ones shown on the mockup below.

2) a scrolling list of "Notes", and a field for the user to type a new note. The mockup below shows this as one big field,  but we should list each note separately. This means we need a data model for storing the notes. We should also store (and display) the username of the person who entered the note, and the date/time it was created.

3) list of tags for the person, with the ability to add more.

4) all contact information about the user.


![wireframepro_-_nationalgroups1](https://user-images.githubusercontent.com/1071298/27048046-283a1a64-4f5f-11e7-9ce8-30f0d088221e.png)

**Comment by Matt-Holland** [comment]
we'll need to do another round of expanding the admin interface to the user record, but this ticket itself is complete. closing.
