### ISSUE TITLE
Pull in Event Creator and Modified By from OSDI links

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#183]
Events have associated creators and modified by records as links.

                    "osdi:creator": {
                        "href": "https://actionnetwork.org/api/v2/people/65345d7d-cd24-466a-a698-4a7686ef684f"
                    },
                     "osdi:modified_by": {
                        "href": "https://actionnetwork.org/api/v2/people/c945d6fe-929e-11e3-a2e9-12313d316c29"
                    },

We should pull those in and set them when an event is imported / synced with AN.

**Comment by agustinrhcp** [comment]
@rabble can you give me an id of an event which has been modified? 
I couldn't find any `modified_by` key

**Comment by rabble** [comment]
i modified a bunch of harpo's events so that should give you data to try out.

**Comment by rabble** [comment]
Checking, it's not pulling in modified by records... but it does record changes to events...  but not changes to their location. (I'll write another ticket for that). 

https://gist.github.com/rabble/f0c7f8ab97649cfa0e651259ad1663a0

**Comment by rabble** [comment]
I can confirm that this DOES work correctly for new events, but not for existing ones.

**Comment by agustinrhcp** [comment]
I'm still not seeing any Event with the modified_by attribute :(

**Comment by agustinrhcp** [comment]
I think they are not returning the modified_by key at all, the creator is already done. I'm moving this ticket to the next column
