### ISSUE TITLE
Add more users and data to AffinityTest on Action Network

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#188]
We need to have at least 51 people records, at least 26 events for the next several months, attendances to those events so we have pagination and other things working. 

Add all these fake data records to AN's Affinity Test group so we have good data to play with on dev and in the review apps.

**Comment by harpojaeger** [comment]
FYI I started this and haven't had time to finish.  Should be done tomorrow.

**Comment by harpojaeger** [comment]
We now have two pages of events, 3 pages of members and one event (http://dev.advocacycommons.org/events/4) with 26 attendees ( #193 notwithstanding).
