### ISSUE TITLE
Travis isn't running for staging deploys, perhaps others.... it' hangs oddly

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#189]
So travis ends with this... 

-- add_foreign_key("twitter_shares", "share_pages")
   -> 0.0014s
-- initialize_schema_migrations_table()
   -> 0.0024s
The command "bundle exec rake db:schema:load" exited with 0.
4.60s$ bundle exec rake db:test:prepare
(in /home/travis/build/advocacycommons/advocacycommons)
The command "bundle exec rake db:test:prepare" exited with 0.
Done. Your build exited with 0.

I'm not sure what's going on, but it seems pretty clearly that it's not running out tests...

**Comment by Matt-Holland** [comment]
@matinieves says this works, closing.
