### ISSUE TITLE
Adding new attendee doesn't update rsvp count

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#197]
When you add a new attendee it doesn't update the rsvp count. 

![screen shot 2017-05-23 at 4 07 09 pm](https://cloud.githubusercontent.com/assets/76/26380200/0e0588f0-3fd2-11e7-9a99-3a1efb5400a8.png)

**Comment by setch-l** [comment]
Need events to test with for organizer@member.com

**Comment by setch-l** [comment]
This works on /attendances but the RSVP count is not updating at the top of the page on the /attendances/new. 

As a local organizer I will likely be adding more than one new attendee on this screen. I want that number to increase at the top of the screen.

**Comment by agustinrhcp** [comment]
@setch-l I removed the `/attendances/new`, now the form will be just on `/attendances`
https://github.com/advocacycommons/advocacycommons/pull/215

**Comment by setch-l** [comment]
@agustinrhcp - I don't see this on production. Has it been deployed?

**Comment by Matt-Holland** [comment]
I tested this on http://www.affinity.works/events/1291/attendances and it works. The rsvp number is only updated once the user clicks "back" to return to the event list page, but that's ok for now.
