### ISSUE TITLE
Affinity not syncing adding new attendee on person record correct.y

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#198]
Syncing doesn't seem to work correctly. It works for NEW people who are created from the form, but not for users who are looked up.

irb(main):006:0> e.attendances[0].person
Person Load (1.3ms) SELECT "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2 [["id", 5], ["LIMIT", 1]]
=> #<Person id: 5, array: nil, family_name: "Jaeger", given_name: "Harpo", additional_name: nil, honorific_prefix: nil, honorific_suffix: nil, gender: nil, gender_identity: nil, party_identification: nil, source: nil, ethnicities: [], languages_spoken: ["en"], birthdate: nil, employer: nil, custom_fields: {}, created_at: "2017-03-17 17:04:27", updated_at: "2017-05-18 22:44:32", identifiers: ["action_network:3d841dbc-ac80-4b4e-9eea-187698c43a56", "advocacycommons:5", "affinity_id:Uj4hU6Xwhr7tuA8W60eEFBkNUij62hqD52cpDINwQGs="], admin: false, provider: nil, uid: nil, synced: true>
irb(main):007:0> e.attendances[1].person
Person Load (11.8ms) SELECT "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2 [["id", 13], ["LIMIT", 1]]
=> #<Person id: 13, array: nil, family_name: "Levinger", given_name: "Josh", additional_name: nil, honorific_prefix: nil, honorific_suffix: nil, gender: nil, gender_identity: nil, party_identification: nil, source: nil, ethnicities: [], languages_spoken: ["en"], birthdate: nil, employer: nil, custom_fields: {}, created_at: "2013-09-14 00:46:40", updated_at: "2017-05-19 22:59:19", identifiers: ["action_network:0dd3390a-ba50-11e3-a134-12313d1576ca", "salsa:61873353", "salsasupporter_afl:61938486", "salsasupporter_org1306:64669263", "salsasupporter_org6405:66641695"], admin: false, provider: nil, uid: nil, synced: true>
irb(main):008:0> e.attendances[2].person
Person Load (10.8ms) SELECT "people".* FROM "people" WHERE "people"."id" = $1 LIMIT $2 [["id", 73], ["LIMIT", 1]]
=> #<Person id: 73, array: nil, family_name: "email user", given_name: "bob teh fake", additional_name: nil, honorific_prefix: nil, honorific_suffix: nil, gender: nil, gender_identity: nil, party_identification: nil, source: nil, ethnicities: [], languages_spoken: ["en"], birthdate: nil, employer: nil, custom_fields: {}, created_at: "2017-05-23 23:32:45", updated_at: "2017-05-23 23:29:53", identifiers: ["advocacycommons:73", "action_network:43850fa7-cb75-4f94-b29a-a6d322257c72", "affinity_id:KvCQgDsDloL9cvhPkO1Rpz273k7Kodj/mwhjLbBmt9Y="], admin: false, provider: nil, uid: nil, synced: true>

Timestamp (EST),First Name,Last Name,Email,Address,City,State,State Abbreviated,Zip Code,Country,Language,Source,Referer
2017-05-23 13:23:24 EST,Harpo,Jaeger,harpo@affinity.works,,Tucson,Arizona,AZ,85701,US,en,"",""
2017-05-23 19:31:03 EST,bob teh fake,email user,bob@fakeemail.com,,,,"",,US,en,"",""

Affinity thinks it's synced but the looked up Person didn't create an attendance correctly for the event.

Looking further it's creating duplicate records in membership.

irb(main):010:0> ms = Membership.where("person_id = 13")
  Membership Load (18.9ms)  SELECT "memberships".* FROM "memberships" WHERE (person_id = 13)
+----+----------+-----------+--------+-------------------------+-------------------------+
| id | group_id | person_id | role   | created_at              | updated_at              |
+----+----------+-----------+--------+-------------------------+-------------------------+
| 13 | 1        | 13        | member | 2017-05-19 03:32:03 UTC | 2017-05-19 03:32:03 UTC |
| 73 | 1        | 13        | member | 2017-05-23 23:06:15 UTC | 2017-05-23 23:06:15 UTC |
+----+----------+-----------+--------+-------------------------+-------------------------+
2 rows in set

**Comment by agustinrhcp** [comment]
@rabble Ok, I'll add an index for membership duplication. 
But I'm not sure what you meant with the syncing issue. The people who are not created from the form are not being synced to action network?
