### ISSUE TITLE
Don't display events with status 'cancelled'

### ISSUE THREAD

**Issue by harpojaeger** [advocacycommons/advocacycommons#201]
AN allows users to cancel an event after it's been created.  It remains in the DB, but its status changes to 'cancelled.'  We shouldn't show such events at /events.

**Comment by Matt-Holland** [comment]
I'm testing this right now, I've cancelled the 7/5/2017
reborn on the 5th of july 
The Whitehouse Evan Henshaw-Plath
event, and am waiting for the system to re-sync

**Comment by Matt-Holland** [comment]
the "cancelled" event was correctly omitted. Closing this ticket.
