### ISSUE TITLE
When syncing an existing event, it doesn't notice and update event location

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#202]
If the location of an event changes on action network we need to change it in our database... currently we're ignoring changes in location information.

https://gist.github.com/rabble/f0c7f8ab97649cfa0e651259ad1663a0

**Comment by Matt-Holland** [comment]
Tested in production using the Affinity Test group in Action Network. Works as expected -- a change in the location information about a published event is picked up on the next sync and published into Affinity.
