### ISSUE TITLE
Move data entry to /record-attendance screen

### ISSUE THREAD

**Issue by setch-l** [advocacycommons/advocacycommons#209]
We're going to move Add New Attendee fields back to the /record-attendance screen. 
User clicks Add New Attendee button and following fields appear in line:
Email, First Name, Last Name, Phone + Save and Cancel buttons
[Screenshot](http://mattplans.altervista.org/affinity/userstoryimages/Record-Attendance-New-Row.png)

Below these field names there will be an Enter Address hyperlink that expands fields for 
Street Address, City, State (drop down) Zip Code 
Save and cancel buttons move down
[Screenshot](http://mattplans.altervista.org/affinity/userstoryimages/Record-Attendance-Address-Expand.png)

**Comment by rabble** [comment]
This is working now in master but i think the flow / buttons aren't right. You can hit save without having any data entered for the person you're adding, and that doesnt seem right. @setch-l  maybe take a look?
