### ISSUE TITLE
Fix bugs in importing people

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#219]
We need to make sure the following use cases work:

Importing a person from action network where we have their record on Affinity with their email but we don't have the joining uuid.

importing a person where we have them as member of different group than originally we had them imported as.

Importing a person where we have a record for the person with that email and an action network UUID but where the UUID is different. 

we need tests for these situations.

**Comment by agustinrhcp** [comment]
@rabble is this still needed?
