### ISSUE TITLE
Create View My Groups Page

### ISSUE THREAD

**Issue by setch-l** [advocacycommons/advocacycommons#221]
#National Organizers need a screen where they can view all of their local groups. 
Groups should be organized in a table view with the following columns: 
Group Name | Location | Tags | Group Owner 
[Screenshot](http://mattplans.altervista.org/affinity/userstoryimages/FacebookEventImport/Natl_Org_All_Groups_with_tags2.png)

Acceptance Criteria
1. Clicking on a Group Names opens Group Members list for that group. 
2. Group Owner links out to member profile screen 
3. Group name, location and order are sortable using up down arrows. 
4. Clicking a + symbol allows a national organizer to add a new tag for a group. 
5. If tags extend beyond a single line, we need to figure out a solution. Option 1 - allow that row to be scrollable. Option 2 - wrap the tags to the next row and make them smaller.

**Comment by Matt-Holland** [comment]
for the first version, just show "all groups on Affinity"
Next version of this ticket will limit by permissions

**Comment by matinieves** [comment]
I think we should create specific tickets for column sorting and tag inline creation.

**Comment by rabble** [comment]
<img width="1160" alt="screen shot 2017-06-02 at 12 29 22 pm" src="https://cloud.githubusercontent.com/assets/76/26741668/30f41b0a-478f-11e7-84fd-05c69a0ba6b4.png">
looks like it's doing double service. ;-)

**Comment by matinieves** [comment]
Hmm wierd, this is how I see it:

![image](https://cloud.githubusercontent.com/assets/702741/26741847/726c247a-47b1-11e7-9b68-c9714385ad50.png)

I will test it in dev.
