### ISSUE TITLE
Clicking Back on New Attendee Add Screend does not clear previously entered info 

### ISSUE THREAD

**Issue by setch-l** [advocacycommons/advocacycommons#229]
Steps to reproduce:
From event - click on RSVPs
Click on Add New Attendee
Add First Name, Last Name
Add Email 
Click Back button before clicking done. 
Click Add New Attendee
Issue: The info I was previously entering is still populated in the fields, should be when I click the back button.

**Comment by Matt-Holland** [comment]
@setch-l can you clarify this? I think you have a typo in your bug description but I'm not sure. You wrote:

"Issue: The info I was previously entering is still populated in the fields, should be when I click the back button."

I assume you meant "the info should *NOT* be still populated in the fields when i click back -- can you confirm?
