### ISSUE TITLE
in the API requests add some scoping, so it's limited to groups

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#25]

**Comment by agustinrhcp** [comment]
Is it possible for a user to not belong to any group? and if it is, what should be the expected behaviour?

**Comment by rabble** [comment]
In the current system all people come from Action Network and all action network imports have a group, so all users must have a group. There are no users without groups in Affinity for now. And likely never will be.

**Comment by agustinrhcp** [comment]
@Matt-Holland  Isn't it working? Could you define the expected behavior?
