### ISSUE TITLE
Nat. Organizer login page: - need “Groups” to go to a listing of groups, and the route /groups instead of /dashboard

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#260]

**Comment by matinieves** [comment]
@Matt-Holland we need clarification here. Right now `All Groups` are under `/groups/:id/affiliates` and the Dashboard (which has no content yet) is under `/groups/:id/dashboard`

**Comment by Matt-Holland** [comment]
the app already works this way, now. The pages weren't set up this way when I wrote the ticket. Nice work!
