### ISSUE TITLE
Remove "Organizing for Affinity" group

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#263]

**Comment by Matt-Holland** [comment]
the issue is that we need to remove the group “Organizing for Affinity” from the database. It seems to be a mistake, because it has exactly the same member list as the group “Test Group” but a different API key.

**Comment by matinieves** [comment]
Is this already done?  I could not find a Group with name `Organizing for Affinity`in production.
This is the Groups name we've got right now:
`["National Network", "SDP MA04", "50 Ways-Rockbridge", "Test Group", "Affiliate Group"]`
