### ISSUE TITLE
add support for reading / writing tags / taggings from Action Network

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#288]
Action Network's OSDI api supports tags and taggings. 

https://actionnetwork.org/docs/v2/taggings

Writing taggings but not tags is allowed on the AN api. 

We want to provide both on our api, pull in any tags and taggings that AN has on people, and be able to write taggings back out to AN.

**Comment by Matt-Holland** [comment]
@rabble: this is already deployed to production, yes?

**Comment by Matt-Holland** [comment]
yes this is in production
