### ISSUE TITLE
Bug - adding attendees isn't saving membership in a group

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#313]
When i add an attendee through the new attendee from it's not saving that person's membership in the group. I believe this is because of the validation of permitted params for address lines.

Started POST "/groups/4/events/33/attendances.json" for ::1 at 2017-06-15 09:14:42 -0700
Processing by AttendancesController#create as JSON
  Parameters: {"attendance"=>{"family_name"=>"asdf", "given_name"=>"asdf", "primary_email_address"=>"asdf@asdf.com", "primary_phone_number"=>"", "primary_personal_address"=>{"address_lines"=>[[]], "postal_code"=>"", "locality"=>""}}, "group_id"=>"4", "event_id"=>"33"}
Geokit is using the domain: localhost
  Person Load (136.0ms)  SELECT  "people".* FROM "people" WHERE "people"."id" = $1 ORDER BY "people"."id" ASC LIMIT $2  [["id", 4], ["LIMIT", 1]]
  Group Load (85.9ms)  SELECT  "groups".* FROM "groups" WHERE "groups"."id" = $1 LIMIT $2  [["id", 4], ["LIMIT", 1]]
   (0.8ms)  SELECT "groups"."id" FROM "groups" INNER JOIN "affiliations" ON "groups"."id" = "affiliations"."affiliated_id" WHERE "affiliations"."group_id" = $1  [["group_id", 4]]
  Event Load (0.9ms)  SELECT  "events".* FROM "events" INNER JOIN "events_groups" ON "events_groups"."event_id" = "events"."id" INNER JOIN "groups" ON "groups"."id" = "events_groups"."group_id" WHERE ("events"."status" != $1) AND "groups"."id" = 4 AND "events"."id" = $2 LIMIT $3  [["status", "cancelled"], ["id", 33], ["LIMIT", 1]]
  Group Load (0.6ms)  SELECT  "groups".* FROM "groups" INNER JOIN "memberships" ON "groups"."id" = "memberships"."group_id" WHERE "memberships"."person_id" = $1 ORDER BY "groups"."id" ASC LIMIT $2  [["person_id", 4], ["LIMIT", 1]]
  CACHE (0.0ms)  SELECT  "groups".* FROM "groups" INNER JOIN "memberships" ON "groups"."id" = "memberships"."group_id" WHERE "memberships"."person_id" = $1 ORDER BY "groups"."id" ASC LIMIT $2  [["person_id", 4], ["LIMIT", 1]]
  Membership Load (24.1ms)  SELECT "memberships".* FROM "memberships" WHERE "memberships"."person_id" = $1 AND "memberships"."role" = $2  [["person_id", 4], ["role", 1]]
  Group Load (0.2ms)  SELECT  "groups".* FROM "groups" WHERE "groups"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Event Load (7.1ms)  SELECT  "events".* FROM "events" WHERE ("events"."status" != $1) AND "events"."id" = $2 LIMIT $3  [["status", "cancelled"], ["id", 33], ["LIMIT", 1]]
Unpermitted parameter: address_lines
  SQL (1.3ms)  SELECT  DISTINCT "people"."id", "people"."id" AS alias_0 FROM "people" LEFT OUTER JOIN "email_addresses" ON "email_addresses"."person_id" = "people"."id" WHERE "email_addresses"."address" = $1 ORDER BY "people"."id" ASC LIMIT $2  [["address", "asdf@asdf.com"], ["LIMIT", 1]]
Unpermitted parameter: address_lines

**Comment by agustinrhcp** [comment]
and if you do in the console `Person.last.memberships.count` it returns 0? 
I just tested it and it worked for me. The unpermitted parameters are just ignored, I'll add them, but that won't break anything

**Comment by matinieves** [comment]
It worked for me too, in which environment are you testing it? Dev?.
