### ISSUE TITLE
Add attendances back to AN

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#328]
When a person is marked as "attended" to an event in Affinity, we need that information to be synced back to Action Network.

The way to do this is to create a new "action" in ActionNetwork using their API. As they say in their documentation:

> " actions created via the API could be thought of as a way to categorize or tag people based on their action history taken using another toolset or platform."

Here are the instructions from ActionNetwork:
https://actionnetwork.org/docs/v2/post-actions/

NOTE that in the tutorial they use the example of ` POST https://actionnetwork.org/api/v2/fundraising_pages/`
However in our case we will want to use `POST https://actionnetwork.org/api/v2/events` instead. Then we will apply an "attendance" for the specified user, to the event we created.

In ActionNetwork an "action" can be an event where people are invited, or it can be an email that is sent, or other things. For our purposes, it is always an event. It is IMPORTANT to understand that for an event created in ActionNetwork, which then collects attendances in Affinity, there will be TWO "actions" in ActionNetwork. The flow is like this:

1) User creates an event in AN, named for instance "weekly meeting"
2) the event is synced to Affinity
3) the users who have an "attendance" for this event are synced to affinity (in other words, the people who have RSVP'd to the event)
4) the user sets the attendance records for people who actually DO come to the event ("attendance" is changed from "null" to "true")
--- new part: ---
5) we create the name for a new "action" in AN, called "ATT weekly meeting"  The name for the event is created by adding "ATT" (abbreviation for "attended") and a space, before the original name of the event.
6) check if that event already exists in ActionNetwork. If not, create it.
7) set the people with attendance=true in Affinity to have "taken the action" with AN for the new action.

OTHER DATA:

A) When creating the new action in AN, it is recommended to send an identifier from the Affinity system, like  "identifiers": [
    "Affinity:12345"
  ],
... be sure this is an identifier which will allow us to find the related event in Affinity if we need to.

B) we should also set "origin_system": "Affinity" for the new Actions which we create

C) we should set some value for these "attendance actions" so that we do NOT re-sync them back to Affinity. We don't want them re-appearing as *normal* events in Affinity later on.

**Comment by agustinrhcp** [comment]
@Matt-Holland Maybe I'm missing something, but the documentation you sent is about creating donations for certain group in action network.

**Comment by Matt-Holland** [comment]
@agustinrhcp I've updated the ticket to explain that we will use the `https://actionnetwork.org/api/v2/events` endpoint instead.

**Comment by agustinrhcp** [comment]
@Matt-Holland So we should follow this documentation https://actionnetwork.org/docs/v2/events ? 
That's the resource we pull when we import events from action network. I'm still confused if we are talking about the same type of events, because if we create an event there we end up showing it in the /events tab on affinity.
