### ISSUE TITLE
have search box show what you can search by

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#347]
make preview text in search box be "search by name or location"

**Comment by jonathanedelman** [comment]
@Matt-Holland @rabble just want to update that I got a concussion at the end of last week, so haven't gotten around to doing any work here. I'm trying to work today, so if i'm still feeling alright, I'll try and knock this out tonight.

**Comment by jonathanedelman** [comment]
Just did this on the `All Members` tab since searching by location doesn't work on the `All Events` tab.

**Comment by Matt-Holland** [comment]
This is ready to deploy to Production.
