### ISSUE TITLE
hide Facebook import button from Events page

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#349]
This feature should not be available to all organizations, because it has several problems, listed below.

	- it stops after the first person who is not matched
	- the facebook link to the person's page is broken
	- UI is a mess
	- need to make the link go to messenger
	- why does it ask for my permissions

**Comment by chloealxandra** [comment]
do you mean these permissions?
![screen shot 2017-07-03 at 10 21 10 pm](https://user-images.githubusercontent.com/15697864/27816077-125d3394-603e-11e7-979a-81d92fbdccc1.png)
I believe that is required for facebook to have an import of event api's and info on people attending (data mining) VS sharing an event link

**Comment by chloealxandra** [comment]
Note to self:
also toggle - https://martinfowler.com/bliki/FeatureToggle.html
learn to toggle in react, but that could just be really easy

**Comment by arnolfontalvo** [comment]
@Matt-Holland I understand you would want to add a new flag field in the admin edit group page to handle this issue. or group and organizations are not the same?.
 
![captura de pantalla 2017-11-02 a la s 10 34 37 a m](https://user-images.githubusercontent.com/763752/32335042-fa21f2ca-bfb9-11e7-9f1c-749765b12e35.png)

**Comment by Matt-Holland** [comment]
Ideally we'd do this with a feature flag, set on an admin page, but for now JUST HIDE THE BUTTON FOR EVERYONE, ALL THE TIME.

**Comment by Matt-Holland** [comment]
this is deployed to production; closing.
