### ISSUE TITLE
add "sort by location" to events list

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#352]

**Comment by chloealxandra** [comment]
how are we setting locality?

code from console:

Address.where("region = 'ME'") // Address.where("postal_code = 'search'")
a = Address.pluck(:id)
a.each {|i| print Event.where("address_id = i")}

**Comment by jonathanedelman** [comment]
@Matt-Holland okay if i take this one for my first issue?

**Comment by nice00xt** [comment]
@jonathanedelman do you have any progress for this issue? I think i found a solution

**Comment by jonathanedelman** [comment]
closing since @nice00xt finished this
