### ISSUE TITLE
set up Cosecha groups

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#356]
[network_group_report_15924_20170704_0211.xlsx](https://github.com/advocacycommons/advocacycommons/files/1122562/network_group_report_15924_20170704_0211.xlsx)

**Comment by Matt-Holland** [comment]
maybe create scripts, which creates an organizer and a random password.
Scripts are in /lib

**Comment by Matt-Holland** [comment]
Do it locally and confirm it works.

**Comment by Matt-Holland** [comment]
1. create the national organizer person as a new person. If the primary email address is correct, will sync with AN
2. create the groups with their API key's and names
3. create the affiliations
4. run the sync and import

**Comment by chloealxandra** [comment]
write a script to handle this will run in console.
setting a random pass to email?
seed the database with this

location is not a priority - map that later

**Comment by Matt-Holland** [comment]
this has been done
