### ISSUE TITLE
improve the Groups Edit page

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#357]
http://dev.affinity.works/groups/1/edit

**Comment by Matt-Holland** [comment]
I'm merging together the items from #355 and #253 here

1. allow organizer to grant organizer permissions to other members
2. related to the "Grant Access" relationships in ticket #252 , we need a screen where an Organizer for Group A can grant access to Group B

**Comment by chloealxandra** [comment]
allow organizer to grant organizer permissions to other members moves to members/edit page
