### ISSUE TITLE
Membership Edit Page

### ISSUE THREAD

**Issue by chloealxandra** [advocacycommons/advocacycommons#359]
- [x] allow organizers to add people as members to group
- [x] allow organizers to add email_addresses for new members (do not require email)
- [x] allow organizers to add phone_numbers for new members
- [ ] allow organizers to edit members in current group
- [ ] organizers can change member roles (mockups pending)
- [x] only organizers can access and edit people and roles
- [x] use react styles on view

@rabble will add mockups for roles task.

**Comment by Matt-Holland** [comment]
closing this old issue, and moving the un-done parts (" allow organizers to edit members in current group" and " organizers can change member roles ") to new issues.
