### ISSUE TITLE
Fix link to facebook profile

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#362]
<img width="395" alt="screen shot 2017-08-30 at 3 03 45 pm" src="https://user-images.githubusercontent.com/76/29897190-9b68ebb4-8d94-11e7-92ce-c7c9e18e59fc.png">

We link to a user's facebook profile various places...

There is a file... ./client/app/bundles/Events/components/FacebookLink.jsx where the edit needs to happen. Probably we also want to modify the rails model to include the link to the facebook url.

**Comment by Matt-Holland** [comment]
fixed. (thanks, @jlev ! )
