### ISSUE TITLE
get "current_group" explicitly from user

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#368]
1. remove the code where we infer the current_group based on the URL
(in application_controller:
  def current_group
    group = Group.find(params[:group_id]) if params[:group_id]
    return group **|| current_user.groups.first**
  end)
2. if current_group is not set, redirect to the profile page for user to select a “current_group”
3. add a link labelled “admin” and one labelled “view” after each group. User clicking that link sets their current_group, and redirects to either the public group page or the group dashboard page, depending on which button is clicked.
4. Find other places in the system where we get the "current_group" from the URL, and remove it -- we should look for "current_group" set explicitly

**Comment by rabble** [comment]
I didn't do step 3 because i think it causes problems you haven't considered. The display of admin / user facing versions of groups needs to be more thought out. Right now if you are the admin and you go to the non-admin page you're stuck.

**Comment by Matt-Holland** [comment]
error report on PR #378

1. visit https://dev-advocacycommons-pr-378.herokuapp.com/admin/login in a new, incognito browser
2. login as organizer@member.com
3. (correctly) be shown the profile page
4. click the link for “national network” group
5. be (correctly) redirected to https://dev-advocacycommons-pr-378.herokuapp.com/groups/1/dashboard
6. flash message tries to appear, but only shows green box at the top of the page, no text, and the page itself is blank

console shows:

application-62757d0d5918662898211ef36476ea88bb9fa23a46f514a062efc5773336d4f4.js:18 TypeError: Cannot read property ‘id’ of null

dashboard.json is not returned, which seems necessary for page display.

**Comment by rabble** [comment]
Ok the profile page has been moved to rails, works now, redirect works... ready for you to review again.

**Comment by Matt-Holland** [comment]
@rabble I'm not sure how to review this -- is there a new PR, from which I can generate a new heroku review app?

**Comment by Matt-Holland** [comment]
is in production
