### ISSUE TITLE
Display any custom fields when we view a person's record

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#373]
As an organizer when viewing the profile of an individual member you should be able to see the keys and values.

**Comment by Matt-Holland** [comment]
As per the Action Network API docs ( https://actionnetwork.org/docs/v2/people#custom_fields ), when we synchronize a person record from Action Network, one of the items that is returned is "An object hash of key/value pairs associated with the person, corresponding to custom fields/questions in Action Network."

We store that in the "people" table, in the text field labelled "custom_fields"

here is an example value for that field:

    member_since: 3/10/17
    paid: "$5.00"
    phone: 304-296-3855
    position: Member
    
here is another:

    phone: '3043654477'

**Comment by Matt-Holland** [comment]
We'd like to display it in the member profile page, like this:

<img width="860" alt="custom_fields_psd___50___rgb_8_" src="https://user-images.githubusercontent.com/1071298/32147006-24a064c0-bcb6-11e7-9ac8-b672aee460f8.png">
