### ISSUE TITLE
double display of logo on failed password reset.

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#379]
As a user who tries to reset their password by putting in an invalid email it displays two logos. It shouldn't do that.

<img width="494" alt="screen shot 2017-09-27 at 1 03 27 pm" src="https://user-images.githubusercontent.com/76/30935096-73f898a8-a384-11e7-8d8e-1a12899dc0ee.png">

**Comment by Matt-Holland** [comment]
This is on the page: http://app.affinity.works/admin/password/new

**Comment by Matt-Holland** [comment]
Confirmed works on Dev. Ready to deploy @rabble
