### ISSUE TITLE
password reset email has wrong link

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#380]
when you click the "forgot my password" link from the admin login page, you receive an email with a link like this:
http://email.mg.affinity.works/c/eJw1jrtqxDAQRb9G7mS0o5dVuFhIttwuRSoz8kix8BNbrON8fZQicOFcTnWodVYJaKrUatcHF41SN02qUzJGjUZKGUWvFWhkSshgdOM0cNFoyZU3lqMgwUmYEMFbvDlVz5imamj7qIjQowgS0PjoHQB5imD7xvrgqqkdct6YvDN4lJ3nWWOMaUn5qs91H48ikea0FG54HMVRuYFSZvKxhyPk7t93eR3DwuQb8O_rY7Tb5_vrS5v8Axd_Vns7Y86l_w_DOk24UN2v8y9kY096

which redirects to a url like this:

http://www.affinity.works/admin/password/edit?reset_password_token=2-xyUk7pYEvg56tz2y-N

BUT the url to which you are redirected should start with "app.affinity.works"

**Comment by rabble** [comment]
Found the bug, fixed it.... it's deployed to production

**Comment by Matt-Holland** [comment]
tested, works.
