### ISSUE TITLE
Public roster

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#389]

**Comment by Matt-Holland** [comment]
This requires further detail from Swing Left (and perhaps checking with other user groups as well...) but the main idea is a listing visible to any *member* of the group, of all the other members of the group. Ideal if we have an email-redirect so that a member can contact another member but not exposing the targeted member's email address (a la Craigslist), but again, this needs more scoping and definition.

**Comment by rabble** [comment]
I think this needs more information about how groups and events work for members. Right now it's minimal i think. We need some wireframes for each member view.

**Comment by nice00xt** [comment]
Hi to remember to have some wireframe to a better understanding for a react view?

**Comment by Matt-Holland** [comment]
from Rabble: Not only render the right data, need to make sure the members can't make requests using JSON to get the full records. Going to be a different ability in the abilities library. "Members can view peers, but not manage them", for example.

**Comment by Matt-Holland** [comment]
<img width="857" alt="member_roster_psd___46_7___background__rgb_8___" src="https://user-images.githubusercontent.com/1071298/33276911-f9d0ddd6-d364-11e7-806f-4e4957425ac0.png">

**Comment by Matt-Holland** [comment]
<img width="857" alt="member_roster_psd___46_7___background__rgb_8___" src="https://user-images.githubusercontent.com/1071298/33277023-4e0d16d0-d365-11e7-86db-4e78b0902618.png">

**Comment by Matt-Holland** [comment]
<img width="552" alt="member_roster_psd___46_7___layer_4__rgb_8___" src="https://user-images.githubusercontent.com/1071298/33325244-b925574c-d41f-11e7-8e10-cc70aa40ef22.png">

**Comment by Matt-Holland** [comment]
<img width="916" alt="untitled-2___50___layer_3__rgb_8___" src="https://user-images.githubusercontent.com/1071298/33325415-324bcdc2-d420-11e7-9fe0-1fb49bf392fd.png">

**Comment by arnolfontalvo** [comment]
@Matt-Holland already tested and approved this. Waiting for @rabble approval.
