### ISSUE TITLE
make a member an organizer

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#404]
As an organizer, I want to view a member's profile page and set them to be an organizer of the current group.

1) find the member using the existing search / list of members
2) click “edit member”
3) see a checkbox for “is an organizer of this group” on the member’s profile page

<img width="886" alt="untitled-1___50___background__rgb_8___" src="https://user-images.githubusercontent.com/1071298/32846832-29dedbb8-c9dd-11e7-8868-833736e99cf3.png">

**Comment by arnolfontalvo** [comment]
@Matt-Holland, should this option be able for the new member page?

**Comment by Matt-Holland** [comment]
@rabble this works on the review app, ready for any review from you, and to deploy to production.
