### ISSUE TITLE
default should be wysiwyg for editing group description

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#416]
<img width="742" alt="screen shot 2017-11-21 at 2 05 29 pm" src="https://user-images.githubusercontent.com/76/33082961-39c41f1a-cec5-11e7-85b9-86a5b47bd316.png">

It should default to wisiwyg not html...

**Comment by nice00xt** [comment]
@rabble just it has to display the editor first right?

**Comment by rabble** [comment]
Yep, not a big deal, just change the default.
