### ISSUE TITLE
Adjust UI for for add events feature

### ISSUE THREAD

**Issue by rabble** [advocacycommons/advocacycommons#433]
On the events page we should have the add events button be in line with search and load from facebook. 

![image](https://user-images.githubusercontent.com/76/33784994-f54ddf46-dc17-11e7-80eb-0766a35f5277.png)

**Comment by mgreich** [comment]
Looks like this may already be completed:

<img width="1130" alt="screenshot 2017-12-19 22 23 41" src="https://user-images.githubusercontent.com/133058/34192452-58bb2240-e50b-11e7-83ed-409c442953fd.png">

**Comment by Matt-Holland** [comment]
deployed to production; closing.
