### ISSUE TITLE
BUG: Visiting group page causes forced privilege de-escalation

### ISSUE THREAD

**Issue by aguestuser** [advocacycommons/advocacycommons#467]
## Acceptance Criteria

* visiting any group page in question should not force logout
* forcing logout should never result in privilege de-escalatoin (out of scope?)

## Bug Report

Mon 08 Jan 2018 04:54:28 PM EST

I tried to select a member from the dashboard of the SDP MA4 NE group http://app.affinity.works/groups/3. When I did this, I got an error "an error occurred while retrieving members" and then it's as if I get kicked out the system as an organizer and I am now viewing the dashboard as a volunteer. I can view upcoming events and link to AN, but can't see anything else. I have to log out and back in again to set things right... I think that at some point in the last few weeks [this started happening].

**Comment by Matt-Holland** [comment]
Matt to get michelle's login and replicate, try to isolate which subsystem is causing the problem.

**Comment by Matt-Holland** [comment]
more detail in #472 closing this as duplicate
