### ISSUE TITLE
Allow group leaders to log in to Affinity and see only events they can view in their corresponding AN group

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#5]

**Comment by davidtaylor** [comment]
Does this mean that we need views for user details or is it a limit for the users that appear in the event list?  I am not sure what view this permission is limited to

**Comment by harpojaeger** [comment]
This is just a limit to the events they have access to in AN.

**Comment by Matt-Holland** [comment]
Rabble: "I think that's done"
