### ISSUE TITLE
mark the people who the organizer has "set status" for to the correct OSDI status in Affinity database

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#6]

**Comment by davidtaylor** [comment]
Note that there is a field for status and a field for attended in the OSDI attendance data model.  We should make sure to use the attended bool flag if a user is confirmed as attended as opposed to creating a status for it.

**Comment by davidtaylor** [comment]
Also the status that are in the mocks do not match the OSDI model.

OSDI options:
"declined”, “tentative”, “accepted”, “cancelled”, “needs action”

We have a status for invited that is not represented that we can remove or decide we want to support.  I recommend not supporting for now since we do not have messaging in the system for the invite process

**Comment by harpojaeger** [comment]
Good call.  I'll update the event_manager mock.

**Comment by davidtaylor** [comment]
I also can not get my head around how to treat the attended flag.  In the OSDI data model it is a bool but I would love to know if we had a positive affirmation that they did not attend.  So 1 if attended, 0 if we marked them as not attending and NULL if we have not marked them.  Bool's don't really work that way but I find that difference in data useful to know if someone failed to show up vs if we have not set their attendece status yet.  This is a detail way in the weeds so can be ignored if needed

**Comment by harpojaeger** [comment]
Agree that's a useful distinction down the road; also agree it's not a priority right now.

**Comment by Matt-Holland** [comment]
If I'm hearing this right: "Attendance" *is* boolean -- either they were there or they weren't. So they didn't come, until we positively affirm that they did.

However, there's a workflow issue, which is that we can't guarantee that the organizer has *done* the work of affirming the attendance. And so in the future a different organizer might look at the activist's record and think they are a "flake" when in fact the issue is that organizer just didn't mark them down.

**Comment by Matt-Holland** [comment]
Review the UX for this and decide if we want series of buttons, or else multi-select, etc.
