### ISSUE TITLE
merge in Scott's ROAR fix for getting organizer for event

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#61]

**Comment by Matt-Holland** [comment]
Rabble reported: " i can do the merge, it's not retrieving the associated organizer and making the join yet, but it's loading it's existence correctly"

**Comment by Matt-Holland** [comment]
This is what prevents us from dispalying the organizer of an event.

**Comment by rabble** [comment]
It's now longer pulling in attendance data at all. ;-(

✔ ~/code/advocacycommons [roar-event-organizer|⚑ 37] 
13:10 $ rake action_network_syncer:sync_groups
I, [2017-05-17T13:22:02.456073 #39771]  INFO -- : Api::ActionNetwork::Events#import! from https://actionnetwork.org/api/v2/events?filter=modified_date%20gt%20%272017-05-17T20:10:15Z%27
E, [2017-05-17T13:22:02.951180 #39771] ERROR -- : #<Roar::Transport::Error: Roar error: #<Net::HTTPForbidden:0x007fe5818d9898>>
E, [2017-05-17T13:22:03.149261 #39771] ERROR -- : #<Roar::Transport::Error: Roar error: #<Net::HTTPForbidden:0x007fe581249de8>>
E, [2017-05-17T13:22:03.339170 #39771] ERROR -- : #<Roar::Transport::Error: Roar error: #<Net::HTTPForbidden:0x007fe5811d14d8>>
D, [2017-05-17T13:22:03.339322 #39771] DEBUG -- : Api::ActionNetwork::Events#import! new: 0 existing: 8 updated: 0
I, [2017-05-17T13:22:03.341660 #39771]  INFO -- : Api::ActionNetwork::People#import! from https://actionnetwork.org/api/v2/people?filter=modified_date%20gt%20%272017-05-17T20:10:15Z%27
E, [2017-05-17T13:22:03.798221 #39771] ERROR -- : #<Roar::Transport::Error: Roar error: #<Net::HTTPForbidden:0x007fe57a7a37c8>>
E, [2017-05-17T13:22:03.999029 #39771] ERROR -- : #<Roar::Transport::Error: Roar error: #<Net::HTTPForbidden:0x007fe57a742ba8>>
E, [2017-05-17T13:22:04.188810 #39771] ERROR -- : #<Roar::Transport::Error: Roar error: #<Net::HTTPForbidden:0x007fe57a6c8b50>>
D, [2017-05-17T13:22:04.188941 #39771] DEBUG -- : Api::ActionNetwork::People#import! new: 0 existing: 8 updated: 0
I, [2017-05-17T13:22:04.297652 #39771]  INFO -- : Api::ActionNetwork::Attendances#import! from https://actionnetwork.org/api/v2/events/4af018f2-75c4-49cc-bbd9-32ac38ddf431/attendances?filter=modified_date%20gt%20%272017-05-17T20:10:15Z%27
E, [2017-05-17T13:22:04.529377 #39771] ERROR -- : #<Roar::Transport::Error: Roar error: #<Net::HTTPForbidden:0x007fe57ea8cb48>>
E, [2017-05-17T13:22:04.772223 #39771] ERROR -- : #<Roar::Transport::Error: Roar error: #<Net::HTTPForbidden:0x007fe57ea77d38>>
E, [2017-05-17T13:22:04.969275 #39771] ERROR -- : #<Roar::Transport::Error: Roar error: #<Net::HTTPForbidden:0x007fe57ea59e00>>
D, [2017-05-17T13:22:04.969461 #39771] DEBUG -- : Api::ActionNetwork::Attendances#import! new: 0 existing: 8 updated: 0
I, [2017-05-17T13:22:04.998021 #39771]  INFO -- : Api::ActionNetwork::Events#import! from https://actionnetwork.org/api/v2/events?filter=modified_date%20gt%20%272017-05-17T20:10:20Z%27
D, [2017-05-17T13:22:05.218815 #39771] DEBUG -- : Module#import! resources: 0 page: 1
D, [2017-05-17T13:22:05.218930 #39771] DEBUG -- : Api::ActionNetwork::Events#import! new: 0 existing: 8 updated: 0
I, [2017-05-17T13:22:05.219374 #39771]  INFO -- : Api::ActionNetwork::People#import! from https://actionnetwork.org/api/v2/people?filter=modified_date%20gt%20%272017-05-17T20:10:20Z%27
D, [2017-05-17T13:22:05.587478 #39771] DEBUG -- : Module#import! resources: 1 page: 1
D, [2017-05-17T13:22:05.828059 #39771] DEBUG -- : Module#import! resources: 0 page: 2
D, [2017-05-17T13:22:05.828227 #39771] DEBUG -- : Api::ActionNetwork::People#import! new: 0 existing: 16 updated: 0
I, [2017-05-17T13:22:05.851563 #39771]  INFO -- : Api::ActionNetwork::Events#import! from https://actionnetwork.org/api/v2/events?filter=modified_date%20gt%20%272017-05-17T20:10:39Z%27
D, [2017-05-17T13:22:06.041387 #39771] DEBUG -- : Module#import! resources: 0 page: 1
D, [2017-05-17T13:22:06.041501 #39771] DEBUG -- : Api::ActionNetwork::Events#import! new: 0 existing: 8 updated: 0
I, [2017-05-17T13:22:06.041894 #39771]  INFO -- : Api::ActionNetwork::People#import! from https://actionnetwork.org/api/v2/people?filter=modified_date%20gt%20%272017-05-17T20:10:39Z%27
D, [2017-05-17T13:22:06.288209 #39771] DEBUG -- : Module#import! resources: 0 page: 1
D, [2017-05-17T13:22:06.288379 #39771] DEBUG -- : Api::ActionNetwork::People#import! new: 0 existing: 8 updated: 0
D, [2017-05-17T13:22:06.305798 #39771] DEBUG -- : ### IMPORT FINISHED ###
✔ ~/code/advocacycommons [roar-event-organizer|⚑ 37]

**Comment by agustinrhcp** [comment]
it didn't import anything. It' seemed the data was already there. Check the new counters, always 0, all existing
Maybe you ran the seeds, the seeds also runs the import so it may be it.

**Comment by setch-l** [comment]
Logged in as organizer from Mountaineers for Progress and did not see organizer for the events in their list. 
Logged in as organizer@member.com and did not see any events for this group. 

Unable to test and verify.
