### ISSUE TITLE
switch where Devise gets email

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#83]
modify Person table to NOT include email
have Devise use an email from Email Addresses table

**Comment by agustinrhcp** [comment]
There's something we need to define: 
Nowadays, the only difference between a person (synced from action network) and a user (a person who can login) is the email attribute in the person table. If I modify the table to NOT include  the email that distinction disappears and we need to know when a password is required.

**Comment by rabble** [comment]
A password is required to login. always. If a user has an account but no password they can recover their password and then login. They shouldn't see anything much because they'll be a member not an organizer of an event. This question isn't something which should block a working login system.

**Comment by agustinrhcp** [comment]
That's not what I asked. Luckily Matt already answered it (:

**Comment by Matt-Holland** [comment]
this now works as intended.
