### ISSUE TITLE
remove API::User & Replace with OAuth

### ISSUE THREAD

**Issue by Matt-Holland** [advocacycommons/advocacycommons#85]
replace it with being able serve OAuth
- need an OAuth provider
- associated table
- find all places where we used API::User and replace with OAuth

**Comment by Matt-Holland** [comment]
Doing research.
- first question: are we providing ourself? answer yes.
- probably using DoorKeeper gem. We think it's the best option.

**Comment by Matt-Holland** [comment]
We'll be an OAuth provider that sets a key and password, and sets a token

**Comment by Matt-Holland** [comment]
We'll also be an OAuth consumer, against omniauth or something, but that's a different ticket

**Comment by Matt-Holland** [comment]
- [ ] See what is the best OAuth provider. Should it be Doorkeeper? Decide which to use.

**Comment by harpojaeger** [comment]
#130 merged, but has the above checklist been completed?  Not sure how to run acceptance tests until that's done.

**Comment by Matt-Holland** [comment]
@rabble says this is done
